In [1]:
#lists : mutable sequence with duplicate items
# ordered: yes, mutable:yes, duplicate:yes

# creating a list
mylist=[2,3,0,4]

# indexing a list
mylist[0], mylist[-1]

# reverse indexing a list
mylist.index(0), mylist.index(4)

In [2]:
mylist=[1,2,3,4]

# in
if 3 in mylist:
    print('present')

#for-in
for x in mylist:
    print(x)

In [3]:
len(mylist)

#internally it calls
mylist.__len__()

4

In [4]:
# counting: mylist.count(item)
mylist=[1,2,2,3,4,2]
print(mylist.count(2))

3


In [5]:
# list.append(item)

mylist.append('lemon')
mylist

[1, 2, 2, 3, 4, 2, 'lemon']

In [6]:
# list.insert(index, item)

mylist.insert(1,'item')
mylist

[1, 'item', 2, 2, 3, 4, 2, 'lemon']

In [7]:
# list.pop() removes last element and returns it

mylist.pop()

'lemon'

In [8]:
# list.pop(index) removes item form given index

mylist=[1,2,3]
print(mylist)
print(mylist.pop(1))
print(mylist)

[1, 2, 3]
2
[1, 3]


In [9]:
# list.clear() : clears the list

mylist.clear()
mylist

[]

In [10]:
# list.reverse() : reverses a list

mylist=[2,3,0,4]
mylist.reverse()
mylist


[4, 0, 3, 2]

In [11]:
# list.sort() : sorts a list

mylist.sort()
mylist

[0, 2, 3, 4]

In [12]:
# above methods changes the original list, in order to sort a list without changing it, use sorted()
# sorted(list)

mylist=[2,3,0,4]
newlist=sorted(mylist)
print(mylist,newlist)

[2, 3, 0, 4] [0, 2, 3, 4]


In [13]:
# list multiplication

mylist=[0]*5
mylist

[0, 0, 0, 0, 0]

In [14]:
# list concatanation

mylist=[2,3,0,4]
mylist+[5]


[2, 3, 0, 4, 5]

In [15]:
# List slicing : list[start:stop:step]

mylist = list(range(10))
mylist[::4]


[0, 4, 8]

In [16]:
# reversing a list

mylist[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [17]:
# Assigning lists does not create a new copy

mylist=[2,3,0,4]
newlist=mylist
newlist[0]=100
mylist

[100, 3, 0, 4]

In [18]:
# However, slicing makes a new copy

mylist=[2,3,0,4]
newlist=mylist[:]
newlist.append('lemon')
print(newlist)
print(mylist)

[2, 3, 0, 4, 'lemon']
[2, 3, 0, 4]


In [19]:
# four methods to copy a list properly

newlist=mylist[:]
newlist=mylist.copy()
newlist=list(mylist)
newlist = [x for x in mylist]

In [20]:
# list comprehension : [f(x) for x in list]
a=[1,2,3,4]
b=[x**2 for x in a]
print(b)

[1, 4, 9, 16]


In [21]:
# list comprehension with condition
b=[x**2 for x in a if x%2==0]
print(b)

[4, 16]


In [22]:
a=[1,2,3,4] 
b="abcd"
c=[(x,y) for x in a for y in b]
print(c)

[(1, 'a'), (1, 'b'), (1, 'c'), (1, 'd'), (2, 'a'), (2, 'b'), (2, 'c'), (2, 'd'), (3, 'a'), (3, 'b'), (3, 'c'), (3, 'd'), (4, 'a'), (4, 'b'), (4, 'c'), (4, 'd')]


In [23]:
# tuples: immutable sequence with duplicate items
# ordered:yes, mutable:no, duplicate:yes

In [24]:
# creating a tuple
mytup=(2,3,0,4)

# or without paranthesis
mytup=2,3,0,4

mytup

(2, 3, 0, 4)

In [25]:
# indexing, reverse indexing and slicing works like lists
mytup[0], mytup[-1], mytup.index(4)

(2, 4, 3)

In [26]:
#in
print(2 in mytup)

# for-in
for x in mytup:
    print(x)

True
2
3
0
4


In [27]:
len(mytup)

4

In [28]:
# counting : tuple.count()

mytup.count(2)

1

In [29]:
# slicing works and is like lists

mytup[:]

(2, 3, 0, 4)

In [30]:
# tuple concatanation 
mytup=(1,2,3,4)
newtup=mytup + (43,)

# notice the comma after single element tuple

In [31]:
# tuple multiplication

mytup=(1,2,3,4)
print(mytup*2)
print(mytup)

(1, 2, 3, 4, 1, 2, 3, 4)
(1, 2, 3, 4)


In [32]:
# tuple unpacing
mytup=(4,5)
x,y=mytup
print(x+y)

9


In [33]:
# Extended tuple unpacing 
# * catches all unassigned elements into a list.

mytup = tuple(range(5))
a,*b,c=mytup
print(a,b,c)

0 [1, 2, 3] 4


In [34]:
# This can also be done with slicing

a,b,c=mytup[0], mytup[1:-1], mytup[-1]
print(a,b,c)

0 (1, 2, 3) 4


In [35]:
# Dictionaries: collection, key-value, mutable, unordered

In [36]:
dic={2:4, 4:5} # Anything  immutable (hashable) can be a key
print(dic)
print(dic[2])

{2: 4, 4: 5}
4


In [37]:
# another way to create a dictionary
# notice here quoted are not needed and = in place of :
dic = dict(a=3,b=5)
print(dic['a'])

3


In [38]:
# deleting an elemet 

dic={'a':3, 'b':5}
print(dic)
del dic['a']
print(dic)

{'a': 3, 'b': 5}
{'b': 5}


In [39]:
# pop

dic={'a':3, 'b':5}
k = dic.pop('b')
print(dic)
print(k)

{'a': 3}
5


In [40]:
# pop() does not work without an argument. popitem() returns the last item as a tuple and removes it.
dic={'a':1, 'b':2, 'c':3}
k = dic.popitem()
print(dic)
print(k)

{'a': 1, 'b': 2}
('c', 3)


In [41]:
# in opeartor 

if 'a' in dic: 
    print(dic['a'])
   
# this is safe to access an item

# try-except can also be used

try:
    k=dic['d']
    print(k)
except:
    print('not present')
    

1
not present


In [42]:
# for-in loop in dictionary

dic={'a':1,'b':2,'c':3}
for x in dic:
    print(x)

for x in dic.keys():
    print(x)
     
for x in dic.values():
    print(x)
   
for x in dic.items():
    print(x)
    

a
b
c
a
b
c
1
2
3
('a', 1)
('b', 2)
('c', 3)


In [43]:
# These methods return a list 

print(dic.keys())
print(dic.values())
print(dic.items())

dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])


In [44]:
# copying a dictionary
newdic = dic.copy()

# or 
newdic=dict(dic)


In [45]:
# Even this works
k=[('a',1),['b',2]]
z=dict(k)
print(z)

{'a': 1, 'b': 2}


In [46]:
# Dictionary update

dic1={'a':1,'b':2}
dic2={'b':4,'c':5, 'd':6}
dic1.update(dic2)
print(dic1)
print(dic2)

{'a': 1, 'b': 4, 'c': 5, 'd': 6}
{'b': 4, 'c': 5, 'd': 6}


In [166]:
# get method: dict.get(key, default)

mydict={'a':1, 'b':2, 'c':3}
print(mydict.get('b',100))
print(mydict.get('gg',100))
print(mydict.get('gg','non existent'))

2
100
non existent


In [47]:
# Sets : collection, unorderd, mutable, no duplicates
myset={1,1,2,3}
myset

{1, 2, 3}

In [48]:
myset=set('Hello')
myset

{'H', 'e', 'l', 'o'}

In [49]:
# add() : for adding one element
myset.add('g')
print(myset)

{'o', 'l', 'H', 'e', 'g'}


In [50]:
# add() : for adding one element

myset={2,3,4,0}
myset.add('g')
print(myset)

{0, 2, 3, 4, 'g'}


In [51]:
# remove():removes on element

myset={2,3,0,4}
myset.remove(0)

print(myset)

# remove gives key error if element does not exits
# discard() : removes an element without givig key error

myset.discard(0)
print(myset)

{2, 3, 4}
{2, 3, 4}


In [52]:
# clear() : clears the set
myset={2,3,0,4}
myset.clear()
print(myset)

set()


In [53]:
# pop() : returns an arbitrary value;
myset=set("hello")
print(myset.pop())
print(myset.pop())
print(myset.pop())

o
l
h


In [54]:
#  for in loop on set

myset={2,3,0,4}
for x in myset:
    print(x)

0
2
3
4


In [55]:
# in
if 2 in myset:
    print('yes')

yes


In [56]:
# some sample sets
odds=set(range(1,10,2))
evens=set(range(2,10,2))
primes={2,3,5,7}

print(odds)
print(evens)
print(primes)

{1, 3, 5, 7, 9}
{8, 2, 4, 6}
{2, 3, 5, 7}


In [57]:
# union of sets
u = odds.union(evens)
print(u)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [58]:
set(list(odds)+list(evens))

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [59]:
# intersection of sets
i=odds.intersection(primes)
print(i)

{3, 5, 7}


In [60]:
#difference of sets : common elements are removed form one set
seta={1,2,3,4,5}
setb={4,5,6,7,8}

diff=seta.difference(setb)
print(diff)

{1, 2, 3}


In [61]:
# symmetric difference: common elements are removed and combined
sydiff=seta.symmetric_difference(setb)
print(sydiff)

{1, 2, 3, 6, 7, 8}


In [62]:
# If original set is to be changed then update() method to be used.
seta.update(setb)
print(seta)



{1, 2, 3, 4, 5, 6, 7, 8}


In [63]:
# intersection update

seta={1,2,3,4}
setb={3,4,5,6}
seta.intersection_update(setb)
print(seta)

{3, 4}


In [64]:
# difference update
seta={1,2,3,4}
setb={3,4,5,6}
seta.difference_update(setb)
print(seta)

{1, 2}


In [65]:
# symmetric difference update
seta={1,2,3,4}
setb={3,4,5,6}
seta.symmetric_difference_update(setb)
print(seta)

{1, 2, 5, 6}


In [66]:
# issubset, issuperset, isdisjoint
seta={1,4}
setb={1,2,3,4}
print(seta.issubset(setb))
print(seta.issuperset(seta))
print(seta.isdisjoint(setb))

True
True
False


In [67]:
# frozenset for immutable set.

In [68]:
# Some discussion about immutibility.
# id(object) : gives id of an object


In [69]:
a=256
b=256
print(id(a))
print(id(b))
print(id(256))

# notice the same id
a is b

140727304476416
140727304476416
140727304476416


True

In [70]:
a=257
b=257
print(id(a))
print(id(b))
print(id(257))

# now notice the different id 
# python keeps an array of intergers between -5 and 256
a is b

2062699714160
2062699714256
2062699714128


False

In [71]:
# is can be used to check equality of two objects
a=2
b=2
a is b


True

In [72]:
# id of mutable object does not change on mutation
a=[1,2,4]
print(a)
print(id(a))
a[0]=56
print(a)
print(id(a))

[1, 2, 4]
2062698300352
[56, 2, 4]
2062698300352


In [73]:
# python immutabl objects
# int, float, bool, string, tuple, frozenset
# python mutable objects: lists, sets and dictionaries
# an immutable object cannot be changed after creation.
# however, it can be reassigned.
# mutable objects like lists inside tuple can be changed.


In [74]:
# Strings : ordered, immutable

mystr="hello world"

print(mystr)
print(mystr[2])


hello world
l


In [75]:
#mystr[0]='k' # this is not supported due to string immutability.

In [76]:
# Multi line strings

mystr='''hello 
how are \
you'''
print(mystr)

# notice newline can be escaped with a backslash.

hello 
how are you


In [77]:
# With strings, indexing, reverse indexing and slicing is like lists.
mystr="hello world"
print(mystr[1])
print(mystr[-1])
print(mystr.index('l'))
print(mystr[::-1])

e
d
2
dlrow olleh


In [78]:
# string concatanation
mystr="hello "+"world"
print(mystr)

hello world


In [79]:
# iterating over string
mystr="hello"
for x in mystr:
    print(x)

h
e
l
l
o


In [80]:
# in operator

if 'h' in mystr:
    print('yes')

yes


In [81]:
#in operator works for substrings.

if 'ello' in mystr:
    print('yes')

yes


In [82]:
#stripping/trimming a string
mystr="     hello      world         "
print(mystr)
mystr=mystr.strip()
print(mystr)

# notice it only removes spaces form begining and end.

     hello      world         
hello      world


In [83]:
# somestring methods

mystr="Hello World"
print(mystr.upper())
print(mystr.lower())
print(mystr.startswith('H'))
print(mystr.endswith('World'))



HELLO WORLD
hello world
True
True


In [84]:
# finding inside string

mystr="hello world"
print(mystr.find('ello'))
print(mystr.find('something'))

1
-1


In [85]:
# finding is also possible with index, however if it does not exist then error will apper.
# therefore .find() is better to use. Or, in can be used to check first.

mystr.index('wor')
#mystr.index('kally') # this will throw an error.



6

In [86]:
# Countng in string with .count()

print(mystr.count('l'))
print(mystr.count('ll')) 

# works for substrings as well


3
1


In [87]:
#.replace()

mystr='hello world'
mystr=mystr.replace('world', 'universe')
print(mystr)

# if it does not find the match string it does nothing

mystr=mystr.replace('anything', 'world')
print(mystr)

hello universe
hello universe


In [88]:
# .split(delimeter) : retuns a list
mystr="hello world, how are you"
mylist = mystr.split()
print(mylist)

# converting back to string
# String.join() is used to convert an iterator into a string.
# separator.join(iterator)

mystr= '-'.join(mylist)
print(mystr)


['hello', 'world,', 'how', 'are', 'you']
hello-world,-how-are-you


In [89]:
# timing comparison of conventional joining and .join()

from timeit import default_timer as timer

start=timer()

mylist=['a']*10**2
mystr=""
for x in mylist:
    mystr+=x+" "
    pass
    
mid=timer()
   
mystr=" ".join(mylist)
end=timer()

print(mid-start)
print(end-mid)
print((mid-start)/(end-mid))

9.700000000001374e-05
3.1200000000009e-05
3.108974358973903


In [90]:
# Collections : Counter, namedtuple, OrderedDict, defaultdict, deque

In [91]:
# Counter

from collections import Counter
a = "abcabbccbacc"
counts=Counter(a)
print(counts)

print(counts.most_common(1))
print(list(counts.elements()))


Counter({'c': 5, 'b': 4, 'a': 3})
[('c', 5)]
['a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c', 'c', 'c']


In [92]:
# namedtuple

from collections import namedtuple

Point = namedtuple('Point', 'x, y')
pt=Point(1,-4)
print(pt)
print(pt.x, pt.y)


Point(x=1, y=-4)
1 -4


In [93]:
# OrderedDict : latest version of dictionaries remembers order so it is useless now.

from collections  import OrderedDict

od=OrderedDict()
od['a']=1
od['b']=3
print(od)

OrderedDict([('a', 1), ('b', 3)])


In [94]:
# defaultdict : same as normal dict but has a defalut value if key is not defined.

from collections import defaultdict
d=defaultdict(int)
d['a']=1
print(d['b'])

# normal dict will throw an error here.

0


In [95]:
# deque  : double ended que

from collections import deque
d=deque()

d.append(1)
d.append(2)
d.appendleft(3)
print(d)

d.pop()
print(d)

d.popleft()
print(d)

d.clear()
print(d)

d.extend([4,5,6])
print(d)

d.extendleft([1,2,3])
print(d)

# notice the order in which extendleft adds elements

d.rotate(1)
print(d)

d.rotate(-2)
print(d)

deque([3, 1, 2])
deque([3, 1])
deque([1])
deque([])
deque([4, 5, 6])
deque([3, 2, 1, 4, 5, 6])
deque([6, 3, 2, 1, 4, 5])
deque([2, 1, 4, 5, 6, 3])


In [96]:
# itertools : product, permutations, combinations, accumulate, groupby and infinite iterators

In [97]:
# product
from itertools import product
a=[1,3]
b=[5,6]
p=product(a,b)
print(list(p))

[(1, 5), (1, 6), (3, 5), (3, 6)]


In [98]:
# permutations
from itertools import permutations
a=[1,2,3]
perm=permutations(a,2)
print(list(perm))

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [99]:
# combinations
from itertools import combinations
a=[1,2,3]
comb=combinations(a,2)
print(list(comb))

[(1, 2), (1, 3), (2, 3)]


In [100]:
# combinations with replacement
from itertools import combinations_with_replacement
a=[1,2,3]
com=combinations_with_replacement(a,2)
print(list(com))

[(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]


In [101]:
# accumulate
from itertools import accumulate
a=[1,2,3]
acc=accumulate(a)
print(list(acc))

[1, 3, 6]


In [102]:
#  groupby 
from itertools import groupby

def f(x):
    return x<3

a=[1,2,3]
g=groupby(a,key=f)
for key,value in g:
    print(list(value))

[1, 2]
[3]


In [103]:
# infinite iterators : count, cycle and repeat

from itertools import count, cycle, repeat

a=[1,2,3]
for x in count(10):
    print(x)
    if x ==14:
        break


10
11
12
13
14


In [104]:
a = [1,2,3]
for x in cycle(a):
    print(x)
    if x ==3:
        break

1
2
3


In [105]:

a=[1,2,3]
for x in  repeat(1,3):
    print(x)

1
1
1


In [106]:
# Lambda functions
# lambda x:f(x)
# lambda x,y:f(x,y)

In [107]:
add2=lambda x:x+2
print(add2(3))

5


In [108]:
mylist=[(12,24),(23,56),(2,54)]
mylist_sorted=sorted(mylist, key=lambda x:x[1])
print(mylist_sorted)

[(12, 24), (2, 54), (23, 56)]


In [109]:
# Sorting an array based on magnitude with this technique.
#sorted(list,key)

mylist=[-34,0,44,-1,12,-39,-2,-5]
newlist=sorted(mylist)
print(newlist)
newlist=sorted(mylist,key=lambda x:x**2)
print(newlist)

[-39, -34, -5, -2, -1, 0, 12, 44]
[0, -1, -2, -5, 12, -34, -39, 44]


In [110]:
# Mapping
# map(func, list)

a=[1,2,3,4]
b=map(lambda x:2*x,a)
print(b)
print(list(b))

# note the list casting of b

[2, 4, 6, 8]


In [111]:
# Filter
# filter(func, list)

a=[1,2,3,4]
b=filter(lambda x:x%2==0, a)
print(b)
print(list(b))

# note the list casting of b

[2, 4]


In [112]:
# JSON
# looks very similar to a dictionary

# converting dict to json
# called serialization or encoding

p = {'str':'string', 'tup':(20,30), 'bool':True}

import json
k=json.dumps(p)
print(k)


# json.dumps() takes optional parameters like indent=4, separators=('; ', '= '), sort_keys=True

{"str": "string", "tup": [20, 30], "bool": true}


In [113]:
# converting from json string to dict
# deserialization or decoding

k='{"str": "string", "tup": [20, 30], "bool": true}'
p=json.loads(k)
print(p)

{'str': 'string', 'tup': [20, 30], 'bool': True}


In [114]:
# json with files

# to dump json into a file
with open('file.json','w') as file:
        json.dump(p, file)
        
# loading json out of a file
with open('file.json', 'r') as file:
    p=json.load(file)
    print(p)
         
# yeah... I dont get this fully yet.    

{'str': 'string', 'tup': [20, 30], 'bool': True}


In [ ]:
# Random numbers

# random module : for sudo random numbers
# secret module : for cryptographically strong random numbers
# numpy moudle : for array of random  numbers

In [140]:
# random module

import random

# seeding : optional
random.seed(1)

# random.random() : a random float between 0 and 1
a = random.random()
print(a)

# random.uniform(start, end) : a random float between range
b=random.uniform(1,15)
print(b)

# random.randint(start, end) : a random int between range; upper bound inclusive
c = random.randint(1,5)
print(c)

# random.randrange(start,  end) : same as above but upper bound not included.

# random.normalvariate(mu, sigma) : something statistical random number.

# random.choice() : picks one element form a list
mylist = [1,2,3,4]
a = random.choice(mylist)
print(a)

# random.sample(list, count) : select multiple elements without repetition
a = random.sample(mylist, 3)
print(a)

# random.choices(list, k=count) : selcts mutiple elements with repetition
a = random.choices(mylist, k=5)
print(a)

# random.shuffle(list) : shuffles a list inplace
random.shuffle(mylist)
print(mylist)

0.13436424411240122
12.864072317121257
1
3
[1, 2, 3]
[2, 2, 1, 2, 4]
[3, 1, 2, 4]


In [149]:
# secrets module : has only three functions

import secrets

# secrets.randbelow(upperbound) : a random integer below upperbound
a = secrets.randbelow(10)
print(a)

# secrets.randbits() : a random int with given number of bits
a = secrets.randbits(4)
print(a)

# secrets.choice(list)
a = secrets.choice(mylist)
print(a)

7
7
4


In [160]:
# numpy module
import numpy as np

# np.random.rand(size) : random list of floats
a = np.random.rand(3)
print(a)

a = np.random.rand(3,3)
print(a)

# np.random.randint(loser, upper, (size)) : list of random integers
a = np.random.randint(1,3, (2,2))
print(a)
# note : size is a tuple, if size is ommited, it returns a single integer
a = np.random.randint(1,2)
print(a)
# upper bound is not inclusive

# np.random.shuffle() : lets leave it for now.




[0.65374322 0.70270996 0.71405182]
[[0.89252524 0.7269316  0.73951294]
 [0.87959372 0.86067382 0.88509496]
 [0.4317584  0.35398172 0.70257556]]
[[1 1]
 [1 2]]
1
